version: '3.8'
services:
  web:
    container_name: dany-react-ecom-backoffice
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "7003:7003"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    networks:
      - dany-react-backoffice

networks:
  dany-react-backoffice:
    driver: bridge